apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: node
  labels:
    name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        imagePullPolicy: Never
        image: node-kubernetes-web:v1
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
      restartPolicy: Always
