apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: node
  labels:
    name: postgres-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - "ReadWriteOnce"
  hostPath: # it's minikube host not yours. Use minicube mount host_path:minicube_path to mount you host dir in minikube
    path: /data/postgresdata2