apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: node
  labels:
    name: postgres-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /data/postgresdata